language: php
php:
    - "5.4"
    - "5.3"
before_script:
    - cp config.php-DEVELOPMENT config.php
    - composer install --dev
script: phpunit -d memory_limit=-1
notification:
    email:
        - dp@ez.no
