imports:
    - {resource: storage_engines/legacy/content.yml}
    - {resource: storage_engines/legacy/content_type.yml}
    - {resource: storage_engines/legacy/external_storage_gateways.yml}
    - {resource: storage_engines/legacy/field_value_converters.yml}
    - {resource: storage_engines/legacy/language.yml}
    - {resource: storage_engines/legacy/location.yml}
    - {resource: storage_engines/legacy/object_state.yml}
    - {resource: storage_engines/legacy/search.yml}
    - {resource: storage_engines/legacy/search_query_handlers.yml}
    - {resource: storage_engines/legacy/section.yml}
    - {resource: storage_engines/legacy/trash.yml}
    - {resource: storage_engines/legacy/url_alias.yml}
    - {resource: storage_engines/legacy/url_wildcard.yml}
    - {resource: storage_engines/legacy/user.yml}

parameters:
    ezpublish.spi.persistence.legacy.class: eZ\Publish\Core\Persistence\Legacy\Handler
    ezpublish.api.storage_engine.legacy.dbhandler.class: eZ\Publish\Core\Persistence\Doctrine\ConnectionHandler
    ezpublish.api.storage_engine.legacy.dbhandler.factory.class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\LegacyDbHandlerFactory
    ezpublish.spi.persistence.legacy.transactionhandler.class: eZ\Publish\Core\Persistence\Legacy\TransactionHandler

services:
    ezpublish.spi.persistence.legacy:
        class: %ezpublish.spi.persistence.legacy.class%
        arguments:
            - @ezpublish.spi.persistence.legacy.content.handler
            - @ezpublish.spi.persistence.legacy.search.handler.content
            - @ezpublish.spi.persistence.legacy.content_type.handler
            - @ezpublish.spi.persistence.legacy.language.handler
            - @ezpublish.spi.persistence.legacy.location.handler
            - @ezpublish.spi.persistence.legacy.search.handler.location
            - @ezpublish.spi.persistence.legacy.object_state.handler
            - @ezpublish.spi.persistence.legacy.section.handler
            - @ezpublish.spi.persistence.legacy.transactionhandler
            - @ezpublish.spi.persistence.legacy.trash.handler
            - @ezpublish.spi.persistence.legacy.url_alias.handler
            - @ezpublish.spi.persistence.legacy.url_wildcard.handler
            - @ezpublish.spi.persistence.legacy.user.handler
        tags:
            - {name: ezpublish.storageEngine, alias: legacy}
        lazy: true

    ezpublish.spi.persistence.legacy.transactionhandler:
        class: %ezpublish.spi.persistence.legacy.transactionhandler.class%
        arguments:
            - @ezpublish.api.storage_engine.legacy.dbhandler
            - @ezpublish.spi.persistence.legacy.content_type.handler.caching
            - @ezpublish.spi.persistence.legacy.language.handler.caching

    ezpublish.api.storage_engine.legacy.dbhandler.factory:
        class: %ezpublish.api.storage_engine.legacy.dbhandler.factory.class%
        arguments: [@ezpublish.api.storage_engine.factory]
        calls:
            - [setContainer, [@service_container]]

    ezpublish.api.storage_engine.legacy.dbhandler:
        class: %ezpublish.api.storage_engine.legacy.dbhandler.class%
        factory_service: ezpublish.api.storage_engine.legacy.dbhandler.factory
        factory_method: buildLegacyDbHandler
        lazy: true

