parameters:
    ezpublish.http_cache.purger.class: eZ\Publish\Core\MVC\Symfony\Cache\Http\InstantCachePurger
    ezpublish.http_cache.purge_client.multi_request.class: eZ\Publish\Core\MVC\Symfony\Cache\Http\PurgeClient
    ezpublish.http_cache.purge_client.single_request.class: eZ\Publish\Core\MVC\Symfony\Cache\Http\PurgeClientSingleRequest
    ezpublish.http_cache.purge_client.http_client.class: eZ\Publish\Core\MVC\Symfony\Cache\Http\MultiCurlClient
    ezpublish.http_cache.purge_client.http_client.timeout: 1          # Timeout, in ms. Setting a low value will emulate an asynchronous request
    ezpublish.http_cache.purge_client.browser.class: Buzz\Browser

services:
    ezpublish.http_cache.purger:
        class: %ezpublish.http_cache.purger.class%
        arguments: [@ezpublish.http_cache.purge_client]

    ezpublish.http_cache.purge_client.multi_request:
        class: %ezpublish.http_cache.purge_client.multi_request.class%
        arguments: [@ezpublish.config.resolver, @ezpublish.http_cache.purge_client.browser]

    ezpublish.http_cache.purge_client.single_request:
        class: %ezpublish.http_cache.purge_client.single_request.class%
        parent: ezpublish.http_cache.purge_client.multi_request

    ezpublish.http_cache.purge_client:
        alias: ezpublish.http_cache.purge_client.single_request

    ezpublish.http_cache.purge_client.browser:
        class: %ezpublish.http_cache.purge_client.browser.class%
        arguments: [@ezpublish.http_cache.purge_client.http_client]

    ezpublish.http_cache.purge_client.http_client:
        class: %ezpublish.http_cache.purge_client.http_client.class%
        arguments: [%ezpublish.http_cache.purge_client.http_client.timeout%]
