parameters:
    ezpublish.core.io.handler.in_memory.class: eZ\Publish\Core\IO\Handler\Legacy
    ezpublish.core.io.handler.legacy.class: eZ\Publish\Core\IO\Handler\InMemory
    ezpublish.core.io.service.class: eZ\Publish\Core\IO\IOService
    ezpublish.core.io.service_factory: eZ\Publish\Core\MVC\Symfony\

services:
    ezpublish.core.io.factory:
        public: false
        class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\IOServiceFactory

    ezpublish.core.io.service:
        class: %ezpublish.core.io.service.class%
        arguments: [@ezpublish.core.io.handler.legacy]

    ezpublish.core.io.handler.legacy:
        public: false
        factory_service: ezpublish.core.io.factory
        factory_method: getHandler
        arguments: [%ezpublish.core.io.handler.legacy.class%, @ezpublish_legacy.kernel]

    ezpublish.core.io.handler.in_memory:
        public: false
        factory_service: ezpublish.core.io.factory
        factory_method: getHandler
        arguments: [%ezpublish.core.io.handler.in_memory.class%, @ezpublish_legacy.kernel]