parameters:
    ezpublish.api.repository.factory.class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\RepositoryFactory
    ezpublish.api.repository.class: eZ\Publish\Core\Repository\Repository
    ezpublish.api.io_handler.class: eZ\Publish\Core\IO\InMemoryHandler
    ezpublish.api.storage_engine.factory.class: eZ\Bundle\EzPublishCoreBundle\ApiLoader\StorageEngineFactory
    ezpublish.api.storage_engine.default: inMemory

    ezpublish.api.content.class: eZ\Publish\Core\Repository\Values\Content\Content
    ezpublish.api.location.class: eZ\Publish\Core\Repository\Values\Content\Location

services:
    ezpublish.api.repository.factory:
        class: %ezpublish.api.repository.factory.class%
        arguments: [@service_container]

    ezpublish.api.repository:
        class: %ezpublish.api.repository.class%
        factory_service: ezpublish.api.repository.factory
        factory_method: buildRepository
        arguments:
            - @ezpublish.api.persistence_handler
            - @ezpublish.api.io_handler

    ezpublish.api.io_handler:
        class: %ezpublish.api.io_handler.class%
        public: false

    ezpublish.api.storage_engine.factory:
        class: %ezpublish.api.storage_engine.factory.class%
        arguments: [@service_container]

    ezpublish.api.persistence_handler:
        class: eZ\Publish\SPI\Persistence\Handler
        factory_service: ezpublish.api.storage_engine.factory
        factory_method: buildStorageEngine
        arguments: [%ezpublish.api.storage_engine.default%]
        public: false
