parameters:
    ezpublish.chain_router.class: eZ\Publish\MVC\Routing\ChainRouter
    ezpublish.siteaccess_router.class: eZ\Publish\MVC\SiteAccess\Router

services:
    ezpublish.chain_router:
        class: %ezpublish.chain_router.class%
        arguments: [@router.request_context, @ezpublish.siteaccess_router]

    ezpublish.siteaccess_router:
        class: %ezpublish.siteaccess_router.class%
        arguments: [%ezpublish.siteaccess.default%, %ezpublish.siteaccess.config%]
