parameters:
    ezpublish.security.firewall_listener.default.class: eZ\Publish\Core\MVC\Symfony\Security\Firewall\Listener
    ezpublish.security.auth.class: eZ\Publish\Core\MVC\Symfony\Security\Authentication\Provider
    ezpublish.security.user_provider.class: eZ\Publish\Core\MVC\Symfony\Security\User\Provider

services:
    # TODO: To be implemented. Use legacy for now (see legacy bundle)
    ezpublish.security.firewall_listener.default:
        class: %ezpublish.security.firewall_listener.default.class%
        abstract: true
        parent: security.authentication.listener.abstract
        calls:
            - [setRepository, [@ezpublish.api.repository]]

    ezpublish.security.auth:
        class: %ezpublish.security.auth.class%
        abstract: true
        arguments:
            - ~     # Will be replaced at compile time by the security factory to be the right user provider
            - @ezpublish.api.repository.lazy

#    TODO: To be implemented, use legacy for now (see legacy bundle)
#    ezpublish.security.auth.entry_point:
#        class: %ezpublish.security.auth.entry_point.default.class%
#        abstract: true

    ezpublish.security.user_provider:
        class: %ezpublish.security.user_provider.class%
        arguments: [@ezpublish.api.repository.lazy]
