parameters:
    ezpublish.security.firewall_listener.default.class: eZ\Publish\Core\MVC\Symfony\Security\Firewall\Listener
    ezpublish.security.authentication_provider.class: eZ\Publish\Core\MVC\Symfony\Security\Authentication\Provider
    ezpublish.security.user_provider.class: eZ\Publish\Core\MVC\Symfony\Security\User\Provider

services:
    ezpublish.security.user_provider:
        class: %ezpublish.security.user_provider.class%
        arguments: [@ezpublish.api.repository.lazy]

    ezpublish.security.authentication_provider:
        class: %ezpublish.security.authentication_provider.class%
        abstract: true
        parent: security.authentication.provider.pre_authenticated
        calls:
            - [setLazyRepository, [@ezpublish.api.repository.lazy]]
