parameters:
    ezpublish.session_set_dynamic_name_listener.class: eZ\Bundle\EzPublishCoreBundle\EventListener\SessionSetDynamicNameListener

services:
    ezpublish.session_set_dynamic_name_listener:
        class: %ezpublish.session_set_dynamic_name_listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_subscriber }

