parameters:

services:
    # Legacy storage engine

    # Alias for backend connection used by eZ Publish storage engine
    # Useful if you need to reuse it in order to access resources not related to eZ Publish, but stored in your backend (e.g. foreign DB tables)
    ezpublish.connection:
        alias: ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.api.storage_engine.legacy:
        alias: ezpublish.spi.persistence.legacy
