parameters:
    ezpublish.spi.persistence.cache.class: eZ\Publish\Core\Persistence\Cache\Handler
    ezpublish.spi.persistence.cache.abstractHandler.class: eZ\Publish\Core\Persistence\Cache\AbstractHandler
    ezpublish.spi.persistence.cache.sectionHandler.class: eZ\Publish\Core\Persistence\Cache\SectionHandler
    ezpublish.spi.persistence.cache.locationHandler.class: eZ\Publish\Core\Persistence\Cache\LocationHandler
    ezpublish.spi.persistence.cache.contentHandler.class: eZ\Publish\Core\Persistence\Cache\ContentHandler
    ezpublish.spi.persistence.cache.contentLanguageHandler.class: eZ\Publish\Core\Persistence\Cache\ContentLanguageHandler
    ezpublish.spi.persistence.cache.contentTypeHandler.class: eZ\Publish\Core\Persistence\Cache\ContentTypeHandler
    ezpublish.spi.persistence.cache.userHandler.class: eZ\Publish\Core\Persistence\Cache\UserHandler
    ezpublish.spi.persistence.cache.searchHandler.class: eZ\Publish\Core\Persistence\Cache\SearchHandler
    ezpublish.spi.persistence.cache.transactionhandler.class: eZ\Publish\Core\Persistence\Cache\TransactionHandler
    ezpublish.spi.persistence.cache.trashHandler.class: eZ\Publish\Core\Persistence\Cache\TrashHandler
    ezpublish.spi.persistence.cache.locationSearchHandler.class: eZ\Publish\Core\Persistence\Cache\LocationSearchHandler
    ezpublish.spi.persistence.cache.urlAliasHandler.class: eZ\Publish\Core\Persistence\Cache\UrlAliasHandler
    ezpublish.spi.persistence.cache.persistenceLogger.class: eZ\Publish\Core\Persistence\Cache\PersistenceLogger
    # Make sure logging is only enabled for debug by default
    ezpublish.spi.persistence.cache.persistenceLogger.enableCallLogging: %kernel.debug%

    # External storage gateways
    ezpublish.fieldType.ezbinaryfile.storage_gateway.class: eZ\Publish\Core\FieldType\BinaryFile\BinaryFileStorage\Gateway\LegacyStorage
    ezpublish.fieldType.externalStorageHandler.ezgmaplocation.gateway.class: eZ\Publish\Core\FieldType\MapLocation\MapLocationStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezimage.storage_gateway.class: eZ\Publish\Core\FieldType\Image\ImageStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezkeyword.storage_gateway.class: eZ\Publish\Core\FieldType\Keyword\KeywordStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezmedia.storage_gateway.class: eZ\Publish\Core\FieldType\Media\MediaStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezrichtext.storage_gateway.class: eZ\Publish\Core\FieldType\RichText\RichTextStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezxmltext.storage_gateway.class: eZ\Publish\Core\FieldType\XmlText\XmlTextStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezurl.storage_gateway.class: eZ\Publish\Core\FieldType\Url\UrlStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezuser.storage_gateway.class: eZ\Publish\Core\FieldType\User\UserStorage\Gateway\LegacyStorage
    ezpublish.fieldType.ezpage.storage_gateway.class: eZ\Publish\Core\FieldType\Page\PageStorage\Gateway\LegacyStorage

services:
    # Persistence cache & Lazy loaded storage engine factory
    ezpublish.spi.persistence.cache:
        class: %ezpublish.spi.persistence.cache.class%
        arguments:
            - @ezpublish.api.storage_engine
            - @ezpublish.spi.persistence.cache.sectionHandler
            - @ezpublish.spi.persistence.cache.locationHandler
            - @ezpublish.spi.persistence.cache.contentHandler
            - @ezpublish.spi.persistence.cache.contentLanguageHandler
            - @ezpublish.spi.persistence.cache.contentTypeHandler
            - @ezpublish.spi.persistence.cache.userHandler
            - @ezpublish.spi.persistence.cache.searchHandler
            - @ezpublish.spi.persistence.cache.transactionhandler
            - @ezpublish.spi.persistence.cache.trashHandler
            - @ezpublish.spi.persistence.cache.locationSearchHandler
            - @ezpublish.spi.persistence.cache.urlAliasHandler
            - @ezpublish.spi.persistence.cache.persistenceLogger

    ezpublish.spi.persistence.cache.persistenceLogger:
        class: %ezpublish.spi.persistence.cache.persistenceLogger.class%
        arguments:
            - %ezpublish.spi.persistence.cache.persistenceLogger.enableCallLogging%

    ezpublish.spi.persistence.cache.abstractHandler:
        class: %ezpublish.spi.persistence.cache.abstractHandler.class%
        abstract:  true
        arguments:
            - @ezpublish.cache_pool.spi.cache.decorator
            - @ezpublish.api.storage_engine
            - @ezpublish.spi.persistence.cache.persistenceLogger

    ezpublish.spi.persistence.cache.sectionHandler:
        class: %ezpublish.spi.persistence.cache.sectionHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.locationHandler:
        class: %ezpublish.spi.persistence.cache.locationHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.contentHandler:
        class: %ezpublish.spi.persistence.cache.contentHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.contentLanguageHandler:
        class: %ezpublish.spi.persistence.cache.contentLanguageHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.contentTypeHandler:
        class: %ezpublish.spi.persistence.cache.contentTypeHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.userHandler:
        class: %ezpublish.spi.persistence.cache.userHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.searchHandler:
        class: %ezpublish.spi.persistence.cache.searchHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.transactionhandler:
        class: %ezpublish.spi.persistence.cache.transactionhandler.class%
        arguments:
            - @ezpublish.cache_pool.spi.cache.decorator
            - @ezpublish.spi.persistence.legacy.transactionhandler
            - @ezpublish.spi.persistence.cache.persistenceLogger

    ezpublish.spi.persistence.cache.trashHandler:
        class: %ezpublish.spi.persistence.cache.trashHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.locationSearchHandler:
        class: %ezpublish.spi.persistence.cache.locationSearchHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    ezpublish.spi.persistence.cache.urlAliasHandler:
        class: %ezpublish.spi.persistence.cache.urlAliasHandler.class%
        parent: ezpublish.spi.persistence.cache.abstractHandler

    # Legacy storage engine

    # Alias for backend connection used by eZ Publish storage engine
    # Useful if you need to reuse it in order to access resources not related to eZ Publish, but stored in your backend (e.g. foreign DB tables)
    ezpublish.connection:
        alias: ezpublish.api.storage_engine.legacy.dbhandler

    ezpublish.api.storage_engine.legacy:
        alias: ezpublish.spi.persistence.legacy

    ezpublish.fieldType.ezbinaryfile.storage_gateway:
        class: %ezpublish.fieldType.ezbinaryfile.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezbinaryfile, identifier: LegacyStorage}

    ezpublish.fieldType.ezkeyword.storage_gateway:
        class: %ezpublish.fieldType.ezkeyword.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezkeyword, identifier: LegacyStorage}

    ezpublish.fieldType.ezmedia.storage_gateway:
        class: %ezpublish.fieldType.ezmedia.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezmedia, identifier: LegacyStorage}

    ezpublish.fieldType.ezrichtext.storage_gateway:
        class: %ezpublish.fieldType.ezrichtext.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezrichtext, identifier: LegacyStorage}

    ezpublish.fieldType.ezxmltext.storage_gateway:
        class: %ezpublish.fieldType.ezxmltext.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezxmltext, identifier: LegacyStorage}

    ezpublish.fieldType.ezurl.storage_gateway:
        class: %ezpublish.fieldType.ezurl.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezurl, identifier: LegacyStorage}

    ezpublish.fieldType.ezpage.storage_gateway:
        class: %ezpublish.fieldType.ezpage.storage_gateway.class%
        calls:
            - [setConnection, [@ezpublish.connection]]

    ezpublish.fieldType.ezimage.storage_gateway:
        class: %ezpublish.fieldType.ezimage.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezimage, identifier: LegacyStorage}

    ezpublish.fieldType.externalStorageHandler.ezgmaplocation.gateway:
        class: %ezpublish.fieldType.externalStorageHandler.ezgmaplocation.gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezgmaplocation, identifier: LegacyStorage}

    ezpublish.fieldType.ezuser.storage_gateway:
        class: %ezpublish.fieldType.ezuser.storage_gateway.class%
        tags:
            - {name: ezpublish.fieldType.externalStorageHandler.gateway, alias: ezuser, identifier: LegacyStorage}

