parameters:
    # Available IO handlers types
    ez_io.available_metadata_handler_types: {}
    ez_io.available_binarydata_handler_types: {}

    # User configured IO handlers
    ez_io.metadata_handlers: {}
    ez_io.binarydata_handlers: {}
