parameters:
    ezpublish.core.io.stream_file_listener.class: eZ\Bundle\EzPublishIOBundle\EventListener\StreamFileListener
    ezpublish.core.io.flysystem.default_adapter.class: League\Flysystem\Adapter\Local
    ezpublish.core.io.flysystem.storage_dir_url_decorator.class: eZ\Publish\Core\IO\UrlDecorator\AbsolutePrefix

services:
    ezpublish.core.io.flysystem.default_adapter:
        class: %ezpublish.core.io.flysystem.default_adapter.class%
        arguments:
            - $io_root_dir$

    ezpublish.core.io.flysystem.storage_dir_url_decorator:
        class: %ezpublish.core.io.flysystem.storage_dir_url_decorator.class%
        calls:
            - [ setPrefix, [ $io_prefix$ ] ]

    ezpublish.core.io.stream_file_listener:
        class: %ezpublish.core.io.stream_file_listener.class%
        arguments:
            - @ezpublish.fieldtype.ezimage.io
        calls:
            - [ setIoPrefix, [ $io_root_dir$ ] ]
        tags:
            - { name: kernel.event_subscriber }
