parameters:
    ezplatform.installer.db_based_installer.class: EzSystems\PlatformInstallerBundle\Installer\DbBasedInstaller
    ezplatform.installer.clean_installer.class: EzSystems\PlatformInstallerBundle\Installer\CleanInstaller

services:
    ezplatform.installer.db_based_installer:
        abstract: true
        class:  %ezplatform.installer.db_based_installer.class%
        arguments: [@database_connection]

    ezplatform.installer.clean_installer:
        class: %ezplatform.installer.clean_installer.class%
        parent: ezplatform.installer.db_based_installer
        tags:
            - {name: ezplatform.installer, type: clean}
