# Internal routes
_ezpublishLocation:
    path: /content/location/{locationId}/{viewType}/{layout}
    defaults:
        _controller: ez_content:viewLocation
        viewType: full
        layout: true

_ezpublishUserHash:
    pattern: /_ez_user
    defaults:
        _controller: ezpublish.controller.user.authentication:getUserHash
    requirements:
        method: AUTHENTICATE
