parameters:
    ezpublish.debug.data_collector.class: eZ\Bundle\EzPublishDebugBundle\Collector\EzPublishDataCollector

services:
    ezpublish.debug.data_collector:
        class: %ezpublish.debug.data_collector.class%
        arguments: [ @ezpublish.spi.persistence.cache.persistenceLogger, @service_container ]
        tags:
            -
                name: data_collector
                template: "EzPublishDebugBundle:Profiler:layout"
                id: "ezpublish.debug.toolbar"
                priority: 300    # EzPublish profiling
